name: mermaid130
channels:
  - simpleitk
  - pytorch
  - conda-forge
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.12.0=pyhd8ed1ab_0
  - astroid=2.3.3=py36_0
  - autopep8=1.4.4=py_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py36he6145b8_1001
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=2.0.0=py36_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.12.5=py36h5fab9bb_1
  - cffi=1.13.1=py36h2e261b9_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.4.7=py36hb60f036_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.68.0=hbc83047_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2.30.0=py_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - flake8=3.7.9=py36_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py36h6f030ca_1002
  - google-auth=1.0.1=py36_0
  - google-auth-oauthlib=0.4.1=py_2
  - graphite2=1.3.13=hf484d3e_1000
  - grpcio=1.33.2=py36he0f7d3b_2
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - importlib_metadata=1.6.1=0
  - intel-openmp=2019.4=243
  - isort=4.3.21=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - jsoncpp=1.8.4=hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.3=py36h7b6447c_0
  - libcurl=7.68.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libiconv=1.15=h516909a_1005
  - libnetcdf=4.6.1=h10edf3e_2
  - libogg=1.3.2=h7b6447c_0
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtheora=1.1.1=h5ab3b9f_1
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.6=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.1.2=h14c3975_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mccabe=0.6.1=py36_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.3=py36hd14ec0e_0
  - numpy-base=1.17.3=py36hde5b4d6_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.43=he1b5a44_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py36_0
  - progressbar2=3.37.1=py36_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.8.2=py_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.5.0=py36_0
  - pycparser=2.19=py36_0
  - pyflakes=2.1.1=py36_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pylint=2.4.4=py36_0
  - pynvml=8.0.4=py_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py36h5fab9bb_3
  - pytest=5.4.3=py36_0
  - pytest-runner=5.2=py_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - python-utils=2.3.0=py36_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.3.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3.1=py36h7b6447c_1
  - readline=7.0=h7b6447c_5
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=3.4.2=py_1
  - setuptools=41.6.0=py36_0
  - simpleitk=1.2.4=py36hf484d3e_0
  - simplejson=3.17.0=py36h7b6447c_0
  - six=1.12.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tbb=2020.0=hfd86e86_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.11.1=py_0
  - torchvision=0.4.2=py36_cu101
  - typed-ast=1.4.1=py36h7b6447c_0
  - vtk=8.1.1=py36h4f1983a_204
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.33.6=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - alabaster==0.7.12
    - altgraph==0.17
    - array2gif==1.0.4
    - attrs==19.3.0
    - babel==2.7.0
    - bleach==3.1.0
    - blosc==1.9.2
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.14
    - decorator==4.4.1
    - defusedxml==0.6.0
    - docutils==0.15.2
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - future==0.18.2
    - idna==2.8
    - imageio==2.6.1
    - imagesize==1.1.0
    - importlib-metadata==0.23
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itk==5.1b1
    - itk-core==5.1b1
    - itk-filtering==5.1b1
    - itk-io==5.1b1
    - itk-numerics==5.1b1
    - itk-registration==5.1b1
    - itk-segmentation==5.1b1
    - jdcal==1.4.1
    - jedi==0.15.1
    - jinja2==2.10.3
    - joblib==0.14.0
    - jsonschema==3.1.1
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mistune==0.8.4
    - more-itertools==7.2.0
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - nbsphinx==0.4.3
    - networkx==2.4
    - nibabel==3.0.1
    - notebook==6.0.2
    - packaging==19.2
    - pandas==0.25.3
    - parso==0.5.1
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - ply==3.11
    - prompt-toolkit==2.0.10
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pydicom==1.3.0
    - pygments==2.4.2
    - pyinstaller==3.6
    - pynrrd==0.4.0
    - pypandoc==1.4
    - pyparsing==2.4.4
    - pyrsistent==0.15.5
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - requests==2.22.0
    - scikit-image==0.17.2
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - send2trash==1.5.0
    - sklearn==0.0
    - snowballstemmer==2.0.0
    - sphinx==2.2.1
    - sphinx-gallery==0.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - statsmodels==0.10.1
    - tensorboardx==2.0
    - terminado==0.8.2
    - testpath==0.4.4
    - tifffile==2020.9.3
    - tornado==6.0.3
    - traitlets==4.3.3
    - urllib3==1.25.6
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==0.6.0
prefix: /home/lintian/anaconda3/envs/mermaid130

